POST http://localhost:8080/api/trip
Content-Type: application/json

{
    "driverId" : 552,
    "carId" : 52,
    "destination" : "Košice",
    "origin" : "Vienna"
}

###
POST http://localhost:8080/api/trip/start/754

###
POST http://localhost:8080/api/trip/end/754

###
GET http://localhost:8080/api/trip/52

###
DELETE http://localhost:8080/api/trip/52

###
GET http://localhost:8080/api/trip
